### ISSUE TITLE
thread 'rustc' has overflowed its stack

### ISSUE THREAD

**Issue by tigerros** [rinja-rs/rinja#283]
I have a recursive macro (which is not infinite) and it's causing the error in the title. Maybe my code is just bad, but I can't be sure since rustc crashes when I try to check. Here's the repo: https://github.com/tigerros/dia-status-rustc-bug. Here's my rustc version:
```
rustc 1.83.0 (90b35a623 2024-11-26)
binary: rustc
commit-hash: 90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf
commit-date: 2024-11-26
host: x86_64-pc-windows-msvc
release: 1.83.0
LLVM version: 19.1.1
```

**Comment by Kijewski** [comment]
The macro `render_items` calls itself. A macro call in rinja is not the same as a function call in rust, as the macro body gets inlined.

But this is indeed a bug. Either we should catch this error and present a proper error message instead of causing a stack overflow, or we should relax the rules and turn macro body into proper functions. The latter option is most likely the far more difficult solution to implement.

**Comment by workingjubilee** [comment]
Bug was reported to https://github.com/rust-lang/rust/issues/134092 but I am classifying it as programmer error. If you have any requests however for how this class of error is reported then we can entertain such requests, it just is not a problem that unbounded recursion can cause a stack overflow in the compiler. At that moment, you _are_ the compiler (or at least, we are running your macro as a dynamic library).

**Comment by Kijewski** [comment]
Yeah, I should probably have been more explicit in my answer: It's a bug in rinja, not rust itself.
