### ISSUE TITLE
Add support for `is defined`

### ISSUE THREAD

**Issue by GuillaumeGomez** [rinja-rs/rinja#62]
This implementation would be **at best** strongly limited to one level: the current struct fields and the declared variables in the template.

It would also need https://github.com/rinja-rs/rinja/issues/47 to be implemented, so that in case the variable/field is not declared, the inner block is not generated, preventing compilation errors.

**Comment by Kijewski** [comment]
Ah, yes, I see the appeal! One big template that contains all the logic for all corner cases, but if e.g. the field `footer: Footer` is missing, then don't fail to compile if the access is guarded.

So, it's not actually an `if`, but more of `#[cfg(has_footer)] { … }`. So, I would say: Let's make it a new keyword instead of an expression:

```jinja2
{% ifdef footer %}
   <footer>{{footer}}</footer>
{% endifdef %}
```

This way it should be much easier to implement and the usage would feel much less magical.

**Comment by GuillaumeGomez** [comment]
Can it be combined with an `else` or any `else if` blocks? Also, how to check if it's not defined? :)

**Comment by Kijewski** [comment]
My implementation works just like the inside of `#[cfg(…)]`:

* `{% ifdef a %}` ← field `a` is present
* `{% ifdef not(a) %}` ← field `a` is not present
* `{% ifdef all(a, b) %}` ← fields `a` and `b` are present
* `{% ifdef any(a, b) %}` ← fields `a` or `b` are present
* any nesting like `{% ifdef any(a, not(b)) %}` ← `a` but not `b` present

I wasn't sure if an else-case is needed, but yeah, it can probably come in handy. I added `{% elifdef … %}` and `{% else %}`.

**Comment by GuillaumeGomez** [comment]
I'm really not fond of the syntax. It means we can't mix it with "normal" `if` conditions. Also the `endifdef` keyword is really not great to read imo. :sweat_smile: 

Maybe let's agree on a syntax before you update your PR.

But before that, what don't you like in the original jinja syntax? For reference:

```jinja
{% if x is defined && y is not defined && x == "12" %}
{% endif %}
```

**Comment by Kijewski** [comment]
I don't think we should muddle the meaning of `{% if %}` nodes: The condition is evaluated at run time and only at run time. `is defined` is the exact opposite: The condition is evaluated at compile time and only at compile time.

What rust code would `{% if x is defined && x == "12" && y is not defined %}` produce? (I reodered the operands from your example.) In rust, you can write `if cfg!(cond) {} else {}`, and the compiler will know at compile time which branch it can cull, but both branches have to be valid. Valid syntax and also valid semantics.

Exactly that is not what we what to achieve with `is defined`, because a branch that is not taken has to have valid syntax, but we don't care about the semantics, e.g. that fields that were referenced even exist. That's the same as rust's `#[cfg(…)] {}` (valid syntax, but semantics are ignored), which is quite distinct from an `if`.

I hope I made my thinking clear why I'd choose to use another syntax than `{% if a is defined %}`. :)

**Comment by GuillaumeGomez** [comment]
Except in rust you can definitely have `if cfg!(cond) && is_true {} else {}`. In here, in all conditions we'd go through them to check if there is a compile-time check and if any of the compile-time conditions is not satisfied, to remove the whole condition. Mixing both of them doesn't sound that crazy to me. We can even add errors in case we have conditions like `if x == "true" && x is defined` because we check for the existence of `x` after checking it.

For the syntax itself, it's need to be something that cannot be confused with a rust function/macro, hence why I think `is (not?) defined` does the job well. It also allows to reduce the amount of work required to switch from an official jinja2 template.

**Comment by Kijewski** [comment]
> Except in rust you can definitely have `if cfg!(cond) && is_true {} else {}`.

Please see <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ebdbb9cb4279948e24d1b50195a0080d>. That's what I meant with "valid semantics". There is no `the_semantics_are_checked_in_here()` function in the scope, so the compilation fails.

Jinja2 adopts to the semantics of Python. In there ↓ will work just fine. `NameError`s are only thrown at runtime, only if the line was hit:

```py
def example():
    if False:
        the_semantics_arent_checked_in_here()

example()
```

What if a user writes `{% if (a is define || b) && c %}`? I wouldn't want to write a [CNF](https://en.wikipedia.org/wiki/Conjunctive_normal_form)/[DNF](https://en.wikipedia.org/wiki/Disjunctive_normal_form) converter just to make this feature work. It would work to allow `{% if X is defined %}` as a special syntax, but it would become a hassle to parse `a is def || b is def && c is def`.

And do you really think someone **needs** to write `{% if x is defined && y is not defined && x == "12" %}` in an actual project?

**Comment by Kijewski** [comment]
> Don't you need to write one for `all(any(a, b), not(d))`?

No, we can simply "execute" the expression: 

https://github.com/rinja-rs/rinja/blob/efdb597bba3be973e2467fb89eb0eed25cb1797b/rinja_derive/src/input.rs#L232-L239

> No but it would allow to write `{% if x is defined && x == "12" %}`, which allows to save one condition (lazyness++).

Hehe, lazyness is a good thing in programmers in most cases. But in my opinion allowing this feature would hurt maintainability. And also, I am too lazy to make it work, but I'd be happy to review your implementation. :D

**Comment by Kijewski** [comment]
If you can make it work, then I'm okay with the syntax. :) It could be useful for expressions, too:

```jinja2
<script>
var has_footer = {{ footer is defined }};
</script>
```

**Comment by GuillaumeGomez** [comment]
A case I need to keep in mind. :+1:
